version: "3.7"
services:
  http_api:
    container_name: calendar-http-api
    build:
      context: .
      dockerfile: ./cmd/calendar_api/Dockerfile.http
    restart: on-failure
    ports:
      - "8888:8888"
    networks:
      - calendar
    depends_on:
      - postgres

  grpc_api:
    container_name: calendar-grpc-api
    build:
      context: .
      dockerfile: ./cmd/calendar_api/Dockerfile.grpc
    restart: on-failure
    ports:
      - "50051:50051"
    networks:
      - calendar
    depends_on:
      - postgres
    environment:
      POSTGRES_DSN: "postgres://postgres:123456789@postgres:5432/calendar"

  scheduler:
    container_name: calendar-scheduler
    build:
      context: .
      dockerfile: ./cmd/calendar_scheduler/Dockerfile
    restart: on-failure
    networks:
      - calendar
    depends_on:
      - postgres
      - rabbit
    environment:
      POSTGRES_DSN: "postgres://postgres:123456789@postgres:5432/calendar"

  sender:
    container_name: calendar-sender
    build:
      context: .
      dockerfile: ./cmd/calendar_sender/Dockerfile
    restart: on-failure
    networks:
      - calendar
    depends_on:
      - rabbit

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    networks:
      - calendar
    volumes:
      - ./sql/postgres_init.sql:/docker-entrypoint-initdb.d/setup.sql

  rabbit:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - calendar
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

networks:
  calendar:
    driver: bridge