version: "3.7"
services:
  integration_tests:
    build: tests
    command: "true"
    links:
      - grpc_api
    environment:
      TESTS_GRPC_LISTEN: "grpc_api:50052"
    networks:
      - rotation

  grpc_api:
    container_name: rotation_grpc-api
    build:
      context: .
      dockerfile: ./cmd/rotation_api/Dockerfile
    restart: on-failure
    ports:
      - "50052:50052"
    networks:
      - rotation
    depends_on:
      - postgres
    environment:
      POSTGRES_DSN: "postgres://postgres:123456789@postgres:5433/banner_rotation"

  postgres:
    container_name: postgres_rotation
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: banner_rotation
    ports:
      - "5433:5432"
    networks:
      - rotation
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/setup.sql

  rabbit:
    container_name: rabbit_rotation
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rotation

networks:
  rotation:
    driver: bridge