version: "3.7"
services:
  api:
    container_name: calendar-api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8888:8888"
    networks:
      - calendar
    depends_on:
      - postgres

  scheduler:
    container_name: calendar-scheduler
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    networks:
      - calendar
    depends_on:
      - postgres
      - rabbit

  sender:
    container_name: calendar-sender
    build:
      context: .
      dockerfile: Dockerfile.sender
    networks:
      - calendar
    depends_on:
      - rabbit

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: calendar
    ports:
      - "5432:5432"
    networks:
      - calendar
    volumes:
      - ./sql/postgres_init.sql:/docker-entrypoint-initdb.d/setup.sql

  rabbit:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - calendar

networks:
  calendar:
    driver: bridge