CREATE TABLE public.banners (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar NOT NULL
);

INSERT INTO public.banners (title) VALUES
('Баннер 1')
,('Баннер 2')
,('Баннер 3')
;

CREATE TABLE public.slots (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar NOT NULL
);

INSERT INTO public.slots (title) VALUES
('Слот 1')
,('Слот 2')
,('Слот 3')
;

CREATE TABLE public.groups (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar NOT NULL
);

INSERT INTO public.groups (title) VALUES
('Старики')
,('Дети')
;

CREATE TABLE public.rotation (
	banner_id int NOT NULL,
	slot_id int NOT NULL,
	started_at timestamp NOT NULL DEFAULT Now(),
	CONSTRAINT rotation_fk FOREIGN KEY (banner_id) REFERENCES public.banners(id),
	CONSTRAINT rotation_fk_2 FOREIGN KEY (slot_id) REFERENCES public.slots(id)
);

CREATE INDEX rotation_banner_id_idx ON public.rotation (banner_id,slot_id);